"""PostgreSQL 16 pre-production baseline (corrected in R2/R3).

Revision ID: aba441bbcc36
This revision was corrected before deployment to any non-disposable environment.
Recreate disposable databases previously built from the old baseline; do not stamp
them as current. See docs/database.md for the reset and verification procedure.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "aba441bbcc36"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("domain", sa.String(length=150), nullable=True),
        sa.Column("is_verified", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "industries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "job_source_records",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_adapter", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_adapter", "external_id", name="uq_job_source_external"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("state_province", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "application_answers",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("normalized_question_key", sa.String(length=100), nullable=False),
        sa.Column("original_question_prompt", sa.Text(), nullable=False),
        sa.Column("answer_value", sa.Text(), nullable=False),
        sa.Column("answer_type", sa.String(length=30), nullable=False),
        sa.Column("is_sensitive", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column(
            "user_approved_for_reuse", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column(
            "last_confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "normalized_question_key", name="uq_app_answer_user_key"),
    )
    op.create_table(
        "application_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("legal_first_name", sa.String(length=100), nullable=False),
        sa.Column("legal_middle_name", sa.String(length=100), nullable=True),
        sa.Column("legal_last_name", sa.String(length=100), nullable=False),
        sa.Column("preferred_name", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=30), nullable=False),
        sa.Column("address_street", sa.String(length=255), nullable=True),
        sa.Column("address_city", sa.String(length=100), nullable=False),
        sa.Column("address_state_province", sa.String(length=100), nullable=False),
        sa.Column("address_postal_code", sa.String(length=30), nullable=False),
        sa.Column("address_country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("github_url", sa.String(length=500), nullable=True),
        sa.Column("portfolio_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "career_preferences",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("work_modes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("employment_types", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "education_records",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("institution_name", sa.String(length=255), nullable=False),
        sa.Column("degree_level", sa.String(length=50), nullable=False),
        sa.Column("major", sa.String(length=150), nullable=False),
        sa.Column("minor", sa.String(length=150), nullable=True),
        sa.Column("study_year", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("expected_grad_month", sa.SmallInteger(), nullable=False),
        sa.Column("expected_grad_year", sa.SmallInteger(), nullable=False),
        sa.Column("gpa_value", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("gpa_scale", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "gpa_include_on_apps", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("expected_grad_month BETWEEN 1 AND 12", name="ck_education_grad_month"),
        sa.CheckConstraint(
            "expected_grad_year BETWEEN 2000 AND 2100", name="ck_education_grad_year"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_education_records_user_id", "education_records", ["user_id"], unique=False)
    op.create_table(
        "employment_records",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("employer_name", sa.String(length=255), nullable=False),
        sa.Column("job_title", sa.String(length=150), nullable=False),
        sa.Column("location", sa.String(length=150), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "currently_employed", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currently_employed = TRUE OR end_date IS NOT NULL", name="ck_employment_end_date"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_employment_records_user_id", "employment_records", ["user_id"], unique=False
    )
    op.create_table(
        "normalized_jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_source_record_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("employment_type", sa.String(length=50), nullable=False),
        sa.Column(
            "career_level",
            sa.String(length=50),
            server_default=sa.text("'UNSPECIFIED'"),
            nullable=False,
        ),
        sa.Column(
            "work_mode",
            sa.String(length=30),
            server_default=sa.text("'UNSPECIFIED'"),
            nullable=False,
        ),
        sa.Column("application_url", sa.String(length=1000), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "last_verified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["job_source_record_id"], ["job_source_records.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_source_record_id"),
    )
    op.create_index("idx_normalized_jobs_company", "normalized_jobs", ["company_id"], unique=False)
    op.create_index(
        "idx_normalized_jobs_discovered", "normalized_jobs", ["discovered_at"], unique=False
    )
    op.create_index(
        "idx_normalized_jobs_role_active", "normalized_jobs", ["role_id", "is_active"], unique=False
    )
    op.create_table(
        "raw_job_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_source_record_id", sa.UUID(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_source_record_id"], ["job_source_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_source_record_id", "payload_hash_sha256", name="uq_job_snapshot_hash"
        ),
    )
    op.create_table(
        "resumes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_resumes_user_id", "resumes", ["user_id"], unique=False)
    op.create_table(
        "skill_aliases",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("normalized_alias", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "normalized_alias", name="uq_skill_alias_normalized"),
    )
    op.create_index("idx_skill_aliases_lookup", "skill_aliases", ["normalized_alias"], unique=False)
    op.create_table(
        "user_preferred_companies",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "company_id"),
    )
    op.create_table(
        "user_preferred_industries",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("industry_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["industry_id"], ["industries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "industry_id"),
    )
    op.create_table(
        "user_preferred_locations",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "location_id"),
    )
    op.create_table(
        "user_preferred_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "user_preferred_skills",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "skill_id"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token_hash"),
    )
    op.create_index("idx_user_sessions_user", "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "user_skills",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column(
            "confirmed_by_user", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False
        ),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("user_notes", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_id", name="uq_user_skill"),
    )
    op.create_index("idx_user_skills_user", "user_skills", ["user_id"], unique=False)
    op.create_table(
        "work_authorizations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("authorization_status", sa.String(length=50), nullable=False),
        sa.Column(
            "requires_current_sponsorship",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column(
            "requires_future_sponsorship",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column(
            "last_confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "country_code", name="uq_work_auth_user_country"),
    )
    op.create_table(
        "career_preference_custom_values",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("career_preference_id", sa.UUID(), nullable=False),
        sa.Column("preference_type", sa.String(length=30), nullable=False),
        sa.Column("value", sa.String(length=150), nullable=False),
        sa.Column("normalized_value", sa.String(length=150), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["career_preference_id"], ["career_preferences.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "career_preference_id", "preference_type", "normalized_value", name="uq_custom_pref_val"
        ),
    )
    op.create_table(
        "job_education_requirements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("degree_level", sa.String(length=50), nullable=False),
        sa.Column("target_grad_start", sa.Date(), nullable=True),
        sa.Column("target_grad_end", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["normalized_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_job_education_reqs_job", "job_education_requirements", ["job_id"], unique=False
    )
    op.create_table(
        "job_eligibility_requirements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("requirement_type", sa.String(length=50), nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_evidence", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["normalized_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_job_eligibility_reqs_job", "job_eligibility_requirements", ["job_id"], unique=False
    )
    op.create_table(
        "job_industries",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("industry_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["industry_id"], ["industries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["normalized_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id", "industry_id"),
    )
    op.create_index("idx_job_industries_industry", "job_industries", ["industry_id"], unique=False)
    op.create_table(
        "job_locations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("location_raw", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["normalized_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_job_locations_job", "job_locations", ["job_id"], unique=False)
    op.create_table(
        "job_skill_requirements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("importance", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["normalized_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "skill_id", name="uq_job_skill_req"),
    )
    op.create_index(
        "idx_job_skill_reqs_lookup", "job_skill_requirements", ["skill_id", "job_id"], unique=False
    )
    op.create_table(
        "resume_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("file_format", sa.String(length=10), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_hash_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "is_primary_active", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column(
            "parse_status",
            sa.String(length=30),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("raw_extracted_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resume_id", "version_number", name="uq_resume_version_num"),
    )
    op.create_index(
        "idx_resume_versions_hash", "resume_versions", ["file_hash_sha256"], unique=False
    )
    op.create_index("idx_resume_versions_resume_id", "resume_versions", ["resume_id"], unique=False)
    op.create_index(
        "idx_user_primary_resume_version",
        "resume_versions",
        ["resume_id"],
        unique=True,
        postgresql_where=sa.text("is_primary_active = TRUE"),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("resume_version_id", sa.UUID(), nullable=True),
        sa.Column("resume_title_snapshot", sa.String(length=150), nullable=True),
        sa.Column("resume_hash_snapshot", sa.CHAR(length=64), nullable=True),
        sa.Column("current_status", sa.String(length=50), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name="ck_application_version"),
        sa.ForeignKeyConstraint(["job_id"], ["normalized_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resume_version_id"], ["resume_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_id", name="uq_app_user_job"),
    )
    op.create_index(
        "idx_applications_user_followup",
        "applications",
        ["user_id", "next_follow_up_at"],
        unique=False,
    )
    op.create_index(
        "idx_applications_user_status", "applications", ["user_id", "current_status"], unique=False
    )
    op.create_table(
        "resume_evaluations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("resume_version_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_type", sa.String(length=50), nullable=False),
        sa.Column("target_role_id", sa.UUID(), nullable=True),
        sa.Column("target_job_id", sa.UUID(), nullable=True),
        sa.Column("rubric_version", sa.String(length=50), nullable=False),
        sa.Column("overall_score", sa.SmallInteger(), nullable=False),
        sa.Column("category_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("itemized_reasons", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("suggested_improvements", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("bullet_analysis_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("overall_score BETWEEN 0 AND 100", name="ck_evaluation_score"),
        sa.ForeignKeyConstraint(["resume_version_id"], ["resume_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_job_id"], ["normalized_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_role_id"], ["roles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_evaluations_resume_version", "resume_evaluations", ["resume_version_id"], unique=False
    )
    op.create_table(
        "resume_evidence_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("resume_version_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("section_header", sa.String(length=150), nullable=True),
        sa.Column("bullet_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["resume_version_id"], ["resume_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_evidence_items_version_id",
        "resume_evidence_items",
        ["resume_version_id"],
        unique=False,
    )
    op.create_table(
        "application_status_histories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("previous_status", sa.String(length=50), nullable=True),
        sa.Column("new_status", sa.String(length=50), nullable=False),
        sa.Column("rejection_stage", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "transitioned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_app_history_app_transitioned",
        "application_status_histories",
        ["application_id", "transitioned_at"],
        unique=False,
    )
    op.create_table(
        "resume_evidence_skills",
        sa.Column("evidence_item_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column(
            "parser_confidence",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("1.00"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_item_id"], ["resume_evidence_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("evidence_item_id", "skill_id"),
    )
    op.create_index(
        "idx_evidence_skills_skill", "resume_evidence_skills", ["skill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_evidence_skills_skill", table_name="resume_evidence_skills")
    op.drop_table("resume_evidence_skills")
    op.drop_index("idx_app_history_app_transitioned", table_name="application_status_histories")
    op.drop_table("application_status_histories")
    op.drop_index("idx_evidence_items_version_id", table_name="resume_evidence_items")
    op.drop_table("resume_evidence_items")
    op.drop_index("idx_evaluations_resume_version", table_name="resume_evaluations")
    op.drop_table("resume_evaluations")
    op.drop_index("idx_applications_user_status", table_name="applications")
    op.drop_index("idx_applications_user_followup", table_name="applications")
    op.drop_table("applications")
    op.drop_index(
        "idx_user_primary_resume_version",
        table_name="resume_versions",
        postgresql_where=sa.text("is_primary_active = TRUE"),
    )
    op.drop_index("idx_resume_versions_resume_id", table_name="resume_versions")
    op.drop_index("idx_resume_versions_hash", table_name="resume_versions")
    op.drop_table("resume_versions")
    op.drop_index("idx_job_skill_reqs_lookup", table_name="job_skill_requirements")
    op.drop_table("job_skill_requirements")
    op.drop_index("idx_job_locations_job", table_name="job_locations")
    op.drop_table("job_locations")
    op.drop_index("idx_job_industries_industry", table_name="job_industries")
    op.drop_table("job_industries")
    op.drop_index("idx_job_eligibility_reqs_job", table_name="job_eligibility_requirements")
    op.drop_table("job_eligibility_requirements")
    op.drop_index("idx_job_education_reqs_job", table_name="job_education_requirements")
    op.drop_table("job_education_requirements")
    op.drop_table("career_preference_custom_values")
    op.drop_table("work_authorizations")
    op.drop_index("idx_user_skills_user", table_name="user_skills")
    op.drop_table("user_skills")
    op.drop_index("idx_user_sessions_user", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_table("user_preferred_skills")
    op.drop_table("user_preferred_roles")
    op.drop_table("user_preferred_locations")
    op.drop_table("user_preferred_industries")
    op.drop_table("user_preferred_companies")
    op.drop_index("idx_skill_aliases_lookup", table_name="skill_aliases")
    op.drop_table("skill_aliases")
    op.drop_index("idx_resumes_user_id", table_name="resumes")
    op.drop_table("resumes")
    op.drop_table("raw_job_snapshots")
    op.drop_index("idx_normalized_jobs_role_active", table_name="normalized_jobs")
    op.drop_index("idx_normalized_jobs_discovered", table_name="normalized_jobs")
    op.drop_index("idx_normalized_jobs_company", table_name="normalized_jobs")
    op.drop_table("normalized_jobs")
    op.drop_index("idx_employment_records_user_id", table_name="employment_records")
    op.drop_table("employment_records")
    op.drop_index("idx_education_records_user_id", table_name="education_records")
    op.drop_table("education_records")
    op.drop_table("career_preferences")
    op.drop_table("application_profiles")
    op.drop_table("application_answers")
    op.drop_index("idx_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_table("skills")
    op.drop_table("roles")
    op.drop_table("locations")
    op.drop_table("job_source_records")
    op.drop_table("industries")
    op.drop_table("companies")
    # ### end Alembic commands ###
